plugins {
    id 'java'
    id 'application'
}

group = 'com.OOP_K02_L'
version = '1.0.0'

repositories {
    mavenCentral()
}

application {
    mainClass = 'main.Main'
}

sourceSets {
    main {
        java.srcDirs = ['src']
        resources.srcDirs = ['res']
    }
}

jar {
    manifest {
        attributes 'Main-Class': 'main.Main'
    }
}